config/routes.rb
Lantrack::Application.routes.draw do

  resources :assignments

  resources :permissions

  resources :roles

  resources :checks

  resources :items

  resources :attends

  resources :events

  resources :attendees
  
  resources :users

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :permission_id, :role_id
end

app/models/attend.rb
class Attend < ActiveRecord::Base
  attr_accessible :attendee_id, :checkedin_at, :checkedout_at, :created_by, :event_id, :is_present
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :attendee_code, :created_by, :first_name, :handle, :last_name, :phone_number
end

app/models/check.rb
class Check < ActiveRecord::Base
  attr_accessible :attendee_id, :created_by, :event_id, :is_checked_in, :item_id
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :created_by, :end_at, :location, :name, :start_at
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :item_code, :created_by, :name, :item_type
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, :class_name => 'User'
  attr_accessible :role_description, :role_name
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role, :class_name => 'Role'
  attr_accessible :created_by, :first_name, :crypt_hash, :last_name, :role_id, :username
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checks }
    end
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
    @check = Check.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/new
  # GET /checks/new.json
  def new
    @check = Check.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/1/edit
  def edit
    @check = Check.find(params[:id])
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(params[:check])

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render json: @check, status: :created, location: @check }
      else
        format.html { render action: "new" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checks/1
  # PUT /checks/1.json
  def update
    @check = Check.find(params[:id])

    respond_to do |format|
      if @check.update_attributes(params[:check])
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check = Check.find(params[:id])
    @check.destroy

    respond_to do |format|
      format.html { redirect_to checks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    
  end
  
  def new
    
  end
  
  def create
    
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checks/_form.html.erb
<%= form_for(@check) do |f| %>
  <% if @check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% @check.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :attendee_id %><br />
    <%= f.number_field :attendee_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :is_checked_in %><br />
    <%= f.check_box :is_checked_in %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<h1>Listing checks</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Attendee</th>
    <th>Event</th>
    <th>Is checked in</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checks.each do |check| %>
  <tr>
    <td><%= check.item_id %></td>
    <td><%= check.attendee_id %></td>
    <td><%= check.event_id %></td>
    <td><%= check.is_checked_in %></td>
    <td><%= check.created_by %></td>
    <td><%= link_to 'Show', check %></td>
    <td><%= link_to 'Edit', edit_check_path(check) %></td>
    <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1>New check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @check.item_id %>
</p>

<p>
  <b>Attendee:</b>
  <%= @check.attendee_id %>
</p>

<p>
  <b>Event:</b>
  <%= @check.event_id %>
</p>

<p>
  <b>Is checked in:</b>
  <%= @check.is_checked_in %>
</p>

<p>
  <b>Created by:</b>
  <%= @check.created_by %>
</p>


<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_code %><br />
    <%= f.text_field :item_code %>
  </div>
  <div class="field">
    <%= f.label :item_type %><br />
    <%= f.number_field :item_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Item Type</th>
    <th>Name</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.item_code %></td>
    <td><%= item.item_type %></td>
    <td><%= item.name %></td>
    <td><%= item.created_by %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @item.item_code %>
</p>

<p>
  <b>Item Type:</b>
  <%= @item.item_type %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Created by:</b>
  <%= @item.created_by %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_name %><br />
    <%= f.text_field :role_name %>
  </div>
  <div class="field">
    <%= f.label :role_description %><br />
    <%= f.text_area :role_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.role_name %></td>
    <td><%= role.role_description %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.role_name %>
</p>

<p>
  <b>Description:</b>
  <%= @role.role_description %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :crypt_hash %><br />
    <%= f.text_area :crypt_hash %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.text_area :role_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_area :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Created_by</th>
    <th>First_name</th>
    <th>Lirst_name</th>
    <th>Crypt Hash</th>
    <th>Role_id</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.created_by %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.crypt_hash %></td>
    <td><%= user.role_id %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>