config/routes.rb
Lantrack::Application.routes.draw do

  resources :assignments

  resources :permissions

  resources :roles

  resources :checks

  resources :items

  resources :attends

  resources :events

  resources :attendees
  
  resources :users

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :permission_id, :role_id
end

app/models/attend.rb
class Attend < ActiveRecord::Base
  attr_accessible :attendee_id, :checkedin_at, :checkedout_at, :created_by, :event_id, :is_present
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :attendee_code, :created_by, :first_name, :handle, :last_name, :phone_number
end

app/models/check.rb
class Check < ActiveRecord::Base
  attr_accessible :attendee_id, :created_by, :event_id, :is_checked_in, :item_id
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :created_by, :end_at, :location, :name, :start_at
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :item_code, :created_by, :name, :item_type
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, :class_name => 'User'
  attr_accessible :role_description, :role_name
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role, :class_name => 'Role'
  attr_accessible :created_by, :first_name, :crypt_hash, :last_name, :role_id, :username
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attends }
    end
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
    @attend = Attend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attend }
    end
  end

  # GET /attends/new
  # GET /attends/new.json
  def new
    @attend = Attend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attend }
    end
  end

  # GET /attends/1/edit
  def edit
    @attend = Attend.find(params[:id])
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(params[:attend])

    respond_to do |format|
      if @attend.save
        format.html { redirect_to @attend, notice: 'Attend was successfully created.' }
        format.json { render json: @attend, status: :created, location: @attend }
      else
        format.html { render action: "new" }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attends/1
  # PUT /attends/1.json
  def update
    @attend = Attend.find(params[:id])

    respond_to do |format|
      if @attend.update_attributes(params[:attend])
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend = Attend.find(params[:id])
    @attend.destroy

    respond_to do |format|
      format.html { redirect_to attends_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    
  end
  
  def new
    
  end
  
  def create
    
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attends/_form.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attendee_id %><br />
    <%= f.number_field :attendee_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :is_present %><br />
    <%= f.check_box :is_present %>
  </div>
  <div class="field">
    <%= f.label :checkedin_at %><br />
    <%= f.datetime_select :checkedin_at %>
  </div>
  <div class="field">
    <%= f.label :checkedout_at %><br />
    <%= f.datetime_select :checkedout_at %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attends/edit.html.erb
<h1>Editing attend</h1>

<%= render 'form' %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

app/views/attends/index.html.erb
<h1>Listing attends</h1>

<table>
  <tr>
    <th>Attendee</th>
    <th>Event</th>
    <th>Is present</th>
    <th>Checkedin at</th>
    <th>Checkedout at</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attends.each do |attend| %>
  <tr>
    <td><%= attend.attendee_id %></td>
    <td><%= attend.event_id %></td>
    <td><%= attend.is_present %></td>
    <td><%= attend.checkedin_at %></td>
    <td><%= attend.checkedout_at %></td>
    <td><%= attend.created_by %></td>
    <td><%= link_to 'Show', attend %></td>
    <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
    <td><%= link_to 'Destroy', attend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attend', new_attend_path %>

app/views/attends/new.html.erb
<h1>New attend</h1>

<%= render 'form' %>

<%= link_to 'Back', attends_path %>

app/views/attends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Attendee:</b>
  <%= @attend.attendee_id %>
</p>

<p>
  <b>Event:</b>
  <%= @attend.event_id %>
</p>

<p>
  <b>Is present:</b>
  <%= @attend.is_present %>
</p>

<p>
  <b>Checkedin at:</b>
  <%= @attend.checkedin_at %>
</p>

<p>
  <b>Checkedout at:</b>
  <%= @attend.checkedout_at %>
</p>

<p>
  <b>Created by:</b>
  <%= @attend.created_by %>
</p>


<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>